### ISSUE TITLE
关于database_util.py

### ISSUE THREAD

**Issue by CN016** [Dr-Left/SCADA-python#1]
这个项目的python版本是多少呢，我用py38 37 39 都不行，无法执行sql语句的函数 
```
ubuntu@VM-12-6-ubuntu:~/SCADA-python$ python3 database_util.py 
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    meth = statement._execute_on_connection
AttributeError: 'str' object has no attribute '_execute_on_connection'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "database_util.py", line 240, in <module>
    work()
  File "database_util.py", line 81, in work
    create_table(conn1, ems_tables)
  File "database_util.py", line 129, in create_table
    connection.execute(drop_lang % table["name"])
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1414, in execute
    raise exc.ObjectNotExecutableError(statement) from err
sqlalchemy.exc.ObjectNotExecutableError: Not an executable object: 'drop table if exists ems_rtu_info'
```

**Comment by Dr-Left** [comment]
我当时用的3.9.16，也许问题原因并不是出在Python版本之上。抱歉我这个项目没有加requirements。我最近查一查你这个问题具体是什么情况再回复您~

**Comment by Dr-Left** [comment]
我搜索到了一个可能的原因是sqlalchemy的版本过新。我当时使用的是1.4.40版本。请退回至2.0版本之前，再次尝试一些也许会可以~

[Reference](https://stackoverflow.com/questions/69490450/objectnotexecutableerror-when-executing-any-sql-query-using-asyncengine)
